apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortis-grimreaper-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortis-grimreaper
  template:
    metadata:
      labels:
        app: mortis-grimreaper
    spec:
      containers:
        - name: mortis-grimreaper
          image: grimreapermortis/mortis-grimreaper:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mortis-grimreaper-secrete
          env:
            - name: NEXTAUTH_URL
              value: http://localhost:8000
          ports:
            - containerPort: 8000
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: front-redis-deployment
#   namespace: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: front-redis
#       role: master
#   template:
#     metadata:
#       labels:
#         app: front-redis
#         role: master
#     spec:
#       containers:
#         - name: redis
#           image: redis:6-alpine
#           # resources:
#           #   requests:
#           #     cpu: 100m
#           #     memory: 100Mi
#           ports:
#             - containerPort: 6379
