apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: grimreapermortis/web-nextjs:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: web-secrete
          env:
            - name: BASE_PATH
              value: /v2/projects
            - name: REDIS_HOST
              value: $(FRONT_REDIS_SERVICE_SERVICE_HOST)
            - name: API_URL
              value: http://$(API_SERVICE_SERVICE_HOST):$(API_SERVICE_SERVICE_PORT)/api
            - name: BOT_HOST
              value: http://$(BOT_SERVICE_SERVICE_HOST):$(BOT_SERVICE_SERVICE_PORT)/bot
            - name: VOID_URL
              value: http://mortis-grimreaper.ddns.net/files

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-redis-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-redis
      role: master
  template:
    metadata:
      labels:
        app: front-redis
        role: master
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          ports:
            - containerPort: 6379
